#!/usr/bin/env python3
"""getbased MCP server — exposes blood work data and knowledge base search as tools.

Architecture:
  getbased (browser) → sync gateway → this MCP → your AI client
                                          ↕
                                    Lens RAG server (Qdrant + BGE-M3)

Blood work data is fetched from the getbased sync gateway.
Knowledge base queries go through the Lens RAG server (separate process).
No models are loaded in this process — everything is HTTP.
"""

import json
import os
import re

import httpx
from mcp.server.fastmcp import FastMCP

mcp = FastMCP("getbased")

# ── Config ───────────────────────────────────────────────────────────
TOKEN = os.environ.get("GETBASED_TOKEN", "")
GATEWAY = os.environ.get("GETBASED_GATEWAY", "https://sync.getbased.health")

LENS_URL = os.environ.get("LENS_URL", f"http://localhost:{os.environ.get('LENS_PORT', '8321')}")
LENS_API_KEY_FILE = os.environ.get(
    "LENS_API_KEY_FILE",
    os.path.expanduser("~/.hermes/rag/lens_api_key"),
)


# ── Helpers ──────────────────────────────────────────────────────────

async def _fetch_context(profile: str = "") -> dict:
    """Fetch formatted lab context from the getbased sync gateway."""
    if not TOKEN:
        return {"error": "GETBASED_TOKEN not set"}
    try:
        params = {"profile": profile} if profile else {}
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.get(
                f"{GATEWAY}/api/context",
                headers={"Authorization": f"Bearer {TOKEN}"},
                params=params,
            )
            r.raise_for_status()
            return r.json()
    except httpx.HTTPStatusError as e:
        return {"error": f"getbased gateway returned {e.response.status_code}"}
    except httpx.RequestError as e:
        return {"error": f"Failed to reach getbased gateway: {e}"}


def _parse_sections(context: str) -> dict[str, str]:
    """Parse [section:name ...]...[/section:name] blocks → {full_name: content}."""
    sections = {}
    for m in re.finditer(
        r"\[section:(\S+)([^\]]*)\]([\s\S]*?)\[/section:\1\]", context
    ):
        base = m.group(1)
        meta = m.group(2).strip()
        full_name = f"{base} {meta}" if meta else base
        sections[full_name] = m.group(3).strip()
    return sections


def _read_lens_key() -> str:
    """Read the Lens API key from file (generated by lens_server.py)."""
    try:
        with open(LENS_API_KEY_FILE) as f:
            key = f.read().strip()
        return key if key else ""
    except (FileNotFoundError, PermissionError, OSError):
        return ""


async def _lens_request(query: str, top_k: int = 5) -> dict:
    """Send a query to the Lens RAG server. Returns parsed JSON or error dict."""
    key = _read_lens_key()
    if not key:
        return {"error": "Lens API key not found. Start lens_server.py first."}
    try:
        async with httpx.AsyncClient(timeout=120) as client:
            r = await client.post(
                f"{LENS_URL}/query",
                headers={"Authorization": f"Bearer {key}"},
                json={"version": 1, "query": query, "top_k": top_k},
            )
            r.raise_for_status()
            return r.json()
    except httpx.ConnectError:
        return {"error": f"Lens server not reachable at {LENS_URL}. Is it running?"}
    except httpx.HTTPStatusError as e:
        return {"error": f"Lens returned {e.response.status_code}: {e.response.text}"}
    except httpx.RequestError as e:
        return {"error": f"Lens request failed: {e}"}
    except (json.JSONDecodeError, ValueError) as e:
        return {"error": f"Lens returned invalid JSON: {e}"}


# ═══════════════════════════════════════════════════════════════════════
# TOOLS — Blood work data
# ═══════════════════════════════════════════════════════════════════════

@mcp.tool()
async def getbased_lab_context(profile: str = "") -> str:
    """Get a full summary of the user's blood work data, health context,
    supplements, and goals from getbased. Use when the user asks broad
    questions about their labs, biomarkers, or health trends.
    Pass a profile ID to query a specific profile, or omit for the default."""
    data = await _fetch_context(profile)
    if "error" in data:
        return f"Error: {data['error']}"
    parts = []
    if data.get("profileId"):
        parts.append(f"Profile: {data['profileId']}")
    if data.get("updatedAt"):
        parts.append(f"Updated: {data['updatedAt']}")
    parts.append(data.get("context", "No context available"))
    return "\n\n".join(parts)


@mcp.tool()
async def getbased_section(section: str = "", profile: str = "") -> str:
    """Get a specific section of health data, or list all available sections.
    Call with no section name to get the index (section names + line counts).
    Call with a section name to get just that section's content.
    Sections include: biometrics, hormones, lipids, hematology, biochemistry,
    supplements, goals, genetics, context cards, etc.
    Section names are matched by prefix.
    Pass a profile ID to query a specific profile, or omit for the default."""
    data = await _fetch_context(profile)
    if "error" in data:
        return f"Error: {data['error']}"
    context = data.get("context", "")
    if not context:
        return "No context available"

    sections = _parse_sections(context)

    if not section:
        lines = []
        for name, content in sections.items():
            count = len([l for l in content.split("\n") if l.strip()])
            lines.append(f"  {name}  ({count} lines)")
        return "Available sections:\n\n" + "\n".join(lines)

    query = section.lower().strip()
    match_key = None
    for k in sections:
        if k.lower() == query:
            match_key = k
            break
    if not match_key:
        for k in sections:
            if k.lower().startswith(query):
                match_key = k
                break
    if not match_key:
        available = [k.split(" ")[0] for k in sections]
        return f'Section "{section}" not found\nAvailable: {", ".join(available)}'

    return f"[{match_key}]\n\n{sections[match_key]}"


@mcp.tool()
async def getbased_list_profiles() -> str:
    """List all available profiles in getbased."""
    data = await _fetch_context()
    if "error" in data:
        return f"Error: {data['error']}"
    profiles = data.get("profiles") or []
    if not profiles:
        return "No profiles found"
    return "\n".join(
        f"{p.get('id', '?')}  {p.get('name', 'unnamed')}" for p in profiles
    )


# ═══════════════════════════════════════════════════════════════════════
# TOOLS — Knowledge base (RAG via Lens server)
# ═══════════════════════════════════════════════════════════════════════

@mcp.tool()
async def knowledge_search(
    query: str,
    n_results: int = 8,
    series: str = "",
    claim_type: str = "",
) -> str:
    """Search the knowledge base for relevant passages using semantic similarity.

    Returns passages from curated health and biology research, organized by
    series and claim type. Use this when the user asks about mechanisms,
    causal relationships, or prescriptive guidance related to health topics.

    Args:
        query: Natural language search query (e.g. "folic acid MTHFR methylation")
        n_results: Number of results to return (default 8, max 10)
        series: Filter to a specific series (e.g. "Decentralized Medicine", "CPC")
        claim_type: Filter to claim type: mechanism, causal, prescriptive, speculative, general
    """
    n_results = max(1, min(10, n_results))

    # TODO: series/claim_type filtering — pass to Lens when it supports metadata filters
    # Currently Lens returns top-k by relevance only. Filter client-side as needed.
    _ = series, claim_type  # acknowledge params until Lens supports them

    data = await _lens_request(query, top_k=n_results)

    if "error" in data:
        return f"Knowledge search error: {data['error']}"

    chunks = data.get("chunks", [])
    if not chunks:
        return "No results found for that query."

    output_lines = []
    for i, chunk in enumerate(chunks):
        text = chunk.get("text", "")
        source = chunk.get("source", "")
        output_lines.append(f"[{i + 1}] {source}")
        output_lines.append(text)
        output_lines.append("")

    return "\n".join(output_lines)


@mcp.tool()
async def getbased_lens_config() -> str:
    """Get the Lens RAG endpoint configuration for getbased's Custom Knowledge Source.
    Returns the URL, API key, and recommended top_k to paste into
    Settings → AI → Custom Knowledge Source in getbased."""
    key = _read_lens_key()
    if not key:
        return (
            "Lens API key not found. Start lens_server.py first to generate one.\n"
            f"Expected key file: {LENS_API_KEY_FILE}"
        )
    return (
        f"Endpoint URL: {LENS_URL}/query\n"
        f"API key (Bearer token): {key}\n"
        f"Recommended top_k: 5\n\n"
        "Paste these into getbased: Settings → AI → Custom Knowledge Source.\n"
        "For production (non-localhost), use HTTPS via a reverse proxy."
    )


if __name__ == "__main__":
    mcp.run()
